### ISSUE TITLE
Integrate the new Pager Facet

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-search#24]
### Description
We need to account for the new FWP "pager" facet type that has been introduced in FacetWP 3.5.4

NB because we select which facets we want to display on the archive via our settings, we can "enable" / "disable" the pager facet by simply unselecting it, or deleting it.
![Screenshot 2020-05-12 at 16 42 52](https://user-images.githubusercontent.com/1805603/81705856-c5db8480-946f-11ea-8fbf-c6a3dd752f0f.png)

### TODO
- [x] Make sure the pager facet does not display in the sidebar by excluding it [here](https://github.com/lightspeeddevelopment/lsx-search/blob/master/classes/class-lsx-search-frontend.php#L704)
- [x] Change the current pager output, first [loop through the facets](https://github.com/lightspeeddevelopment/lsx-search/blob/master/classes/class-lsx-search-frontend.php#L703) and see if there is a pager facet selected.  If so use it, if not output the default. The pager html is [here](https://github.com/lightspeeddevelopment/lsx-search/blob/master/classes/class-lsx-search-frontend.php#L633)
- [x] Pagination numbers should look like the current pagination numbers.
- [x] The load more should use the LSX Border button, like the pagination does. Or the LSX Primary classes.
